import type { ThemeName } from "./types";

type ThemeTokens = Record<string, string>;

const THEME_TOKENS: Record<ThemeName, ThemeTokens> = {
  "xp-blue": {
    "--app-background": "linear-gradient(180deg, #3f6dc1 0%, #9dbde7 100%)",
    "--window-frame": "#0831d9",
    "--window-frame-dark": "#001b7d",
    "--window-frame-light": "#6da8ff",
    "--window-body": "#ece9d8",
    "--window-body-shadow": "#9f9c90",
    "--titlebar-start": "#0a49e6",
    "--titlebar-end": "#3c91ff",
    "--titlebar-text": "#ffffff",
    "--titlebar-inactive-start": "#7c9fd3",
    "--titlebar-inactive-end": "#b8cbe8",
    "--menu-text": "#111111",
    "--panel-face": "#c0c0c0",
    "--panel-shadow": "#808080",
    "--panel-highlight": "#ffffff",
    "--panel-outline": "#404040",
    "--counter-bg": "#030303",
    "--counter-text": "#ff3131",
    "--board-bg": "#bdbdbd",
    "--cell-hidden": "#c0c0c0",
    "--cell-hidden-shadow": "#7b7b7b",
    "--cell-hidden-highlight": "#ffffff",
    "--cell-revealed": "#c0c0c0",
    "--cell-revealed-border": "#7b7b7b",
    "--cell-hover": "#f5f5f5",
    "--mine-color": "#111111",
    "--mine-shine": "#f6f6f6",
    "--flag-red": "#e12727",
    "--flag-pole": "#1e1e1e",
    "--flag-base": "#1e1e1e",
    "--exploded-bg": "#d84e4e",
    "--text-primary": "#111111",
    "--text-secondary": "#2c2c2c",
    "--text-muted": "#5b5b5b",
    "--trainer-safe": "rgba(51, 185, 89, 0.42)",
    "--trainer-risk": "rgba(218, 64, 64, 0.5)",
    "--trainer-text": "#132713",
    "--surface-raised": "#d4d0c8",
    "--surface-raised-dark": "#9d9a93",
    "--surface-raised-light": "#ffffff",
    "--surface-sunken": "#808080",
    "--surface-sunken-light": "#dfdfdf",
    "--ui-font": "Tahoma, \"MS Sans Serif\", sans-serif",
  },
  "xp-olive": {
    "--app-background": "linear-gradient(180deg, #6f7d3b 0%, #d4d9ad 100%)",
    "--window-frame": "#596d2a",
    "--window-frame-dark": "#334210",
    "--window-frame-light": "#9ab468",
    "--window-body": "#ece9d8",
    "--window-body-shadow": "#918c79",
    "--titlebar-start": "#77954b",
    "--titlebar-end": "#b3c66d",
    "--titlebar-text": "#ffffff",
    "--titlebar-inactive-start": "#8fa77b",
    "--titlebar-inactive-end": "#c2d0b4",
    "--menu-text": "#111111",
    "--panel-face": "#c0c0c0",
    "--panel-shadow": "#808080",
    "--panel-highlight": "#ffffff",
    "--panel-outline": "#404040",
    "--counter-bg": "#030303",
    "--counter-text": "#ff3131",
    "--board-bg": "#bdbdbd",
    "--cell-hidden": "#c0c0c0",
    "--cell-hidden-shadow": "#7b7b7b",
    "--cell-hidden-highlight": "#ffffff",
    "--cell-revealed": "#c0c0c0",
    "--cell-revealed-border": "#7b7b7b",
    "--cell-hover": "#f5f5f5",
    "--mine-color": "#111111",
    "--mine-shine": "#f6f6f6",
    "--flag-red": "#e12727",
    "--flag-pole": "#1e1e1e",
    "--flag-base": "#1e1e1e",
    "--exploded-bg": "#d84e4e",
    "--text-primary": "#111111",
    "--text-secondary": "#2c2c2c",
    "--text-muted": "#5b5b5b",
    "--trainer-safe": "rgba(67, 165, 77, 0.42)",
    "--trainer-risk": "rgba(201, 78, 47, 0.48)",
    "--trainer-text": "#14210e",
    "--surface-raised": "#d4d0c8",
    "--surface-raised-dark": "#9d9a93",
    "--surface-raised-light": "#ffffff",
    "--surface-sunken": "#808080",
    "--surface-sunken-light": "#dfdfdf",
    "--ui-font": "Tahoma, \"MS Sans Serif\", sans-serif",
  },
  "xp-silver": {
    "--app-background": "linear-gradient(180deg, #7e8ca8 0%, #d8e0ec 100%)",
    "--window-frame": "#5a6b96",
    "--window-frame-dark": "#334060",
    "--window-frame-light": "#b8c3da",
    "--window-body": "#ece9d8",
    "--window-body-shadow": "#9c998f",
    "--titlebar-start": "#7888b0",
    "--titlebar-end": "#9fb3d8",
    "--titlebar-text": "#ffffff",
    "--titlebar-inactive-start": "#9aa5ba",
    "--titlebar-inactive-end": "#cfd5df",
    "--menu-text": "#111111",
    "--panel-face": "#c0c0c0",
    "--panel-shadow": "#808080",
    "--panel-highlight": "#ffffff",
    "--panel-outline": "#404040",
    "--counter-bg": "#030303",
    "--counter-text": "#ff3131",
    "--board-bg": "#bdbdbd",
    "--cell-hidden": "#c0c0c0",
    "--cell-hidden-shadow": "#7b7b7b",
    "--cell-hidden-highlight": "#ffffff",
    "--cell-revealed": "#c0c0c0",
    "--cell-revealed-border": "#7b7b7b",
    "--cell-hover": "#f5f5f5",
    "--mine-color": "#111111",
    "--mine-shine": "#f6f6f6",
    "--flag-red": "#e12727",
    "--flag-pole": "#1e1e1e",
    "--flag-base": "#1e1e1e",
    "--exploded-bg": "#d84e4e",
    "--text-primary": "#111111",
    "--text-secondary": "#2c2c2c",
    "--text-muted": "#5b5b5b",
    "--trainer-safe": "rgba(70, 143, 195, 0.42)",
    "--trainer-risk": "rgba(212, 90, 90, 0.48)",
    "--trainer-text": "#0f2030",
    "--surface-raised": "#d4d0c8",
    "--surface-raised-dark": "#9d9a93",
    "--surface-raised-light": "#ffffff",
    "--surface-sunken": "#808080",
    "--surface-sunken-light": "#dfdfdf",
    "--ui-font": "Tahoma, \"MS Sans Serif\", sans-serif",
  },
  graphite: {
    "--app-background": "linear-gradient(180deg, #1d2635 0%, #47536b 100%)",
    "--window-frame": "#0f1726",
    "--window-frame-dark": "#050a14",
    "--window-frame-light": "#69748c",
    "--window-body": "#d8d8d8",
    "--window-body-shadow": "#7b7b7b",
    "--titlebar-start": "#1d2d45",
    "--titlebar-end": "#516684",
    "--titlebar-text": "#ffffff",
    "--titlebar-inactive-start": "#5d6576",
    "--titlebar-inactive-end": "#8a95a6",
    "--menu-text": "#111111",
    "--panel-face": "#bcbcbc",
    "--panel-shadow": "#666666",
    "--panel-highlight": "#ffffff",
    "--panel-outline": "#262626",
    "--counter-bg": "#030303",
    "--counter-text": "#ff5959",
    "--board-bg": "#adadad",
    "--cell-hidden": "#bcbcbc",
    "--cell-hidden-shadow": "#666666",
    "--cell-hidden-highlight": "#ffffff",
    "--cell-revealed": "#bcbcbc",
    "--cell-revealed-border": "#666666",
    "--cell-hover": "#efefef",
    "--mine-color": "#111111",
    "--mine-shine": "#f2f2f2",
    "--flag-red": "#ef3b3b",
    "--flag-pole": "#111111",
    "--flag-base": "#111111",
    "--exploded-bg": "#d14a4a",
    "--text-primary": "#101010",
    "--text-secondary": "#232323",
    "--text-muted": "#555555",
    "--trainer-safe": "rgba(56, 174, 118, 0.4)",
    "--trainer-risk": "rgba(212, 84, 84, 0.48)",
    "--trainer-text": "#112018",
    "--surface-raised": "#d4d0c8",
    "--surface-raised-dark": "#7c7c7c",
    "--surface-raised-light": "#ffffff",
    "--surface-sunken": "#585858",
    "--surface-sunken-light": "#dcdcdc",
    "--ui-font": "Tahoma, \"MS Sans Serif\", sans-serif",
  },
};

export function applyTheme(theme: ThemeName): void {
  const root = document.documentElement;
  root.dataset.theme = theme;

  for (const [token, value] of Object.entries(THEME_TOKENS[theme])) {
    root.style.setProperty(token, value);
  }
}
